FROM jboss/wildfly:8.2.1.Final

RUN mkdir -p /opt/jboss/wildfly/standalone/deployments/ROOT.war
RUN touch /opt/jboss/wildfly/standalone/deployments/ROOT.war.dodeploy

VOLUME ["/opt/jboss/wildfly/standalone/deployments/ROOT.war/"]

